version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_delivery
    restart: always
    environment:
      POSTGRES_DB: deliveryDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - "5435:5432"
    networks:
      - postgres

  redis:
    image: redis
    container_name: redis_delivery
    restart: always
    ports:
      - "6397:6379"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
