version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_product
    restart: always
    environment:
      POSTGRES_DB: productDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    networks:
      - postgres

  redis:
    image: redis
    container_name: redis_product
    restart: always
    ports:
      - "6392:6379"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
