spring:
  application:
    name: supplier-server # <--- This is the name it registers with in Eureka
  datasource:
    url: jdbc:postgresql://localhost:5431/supplierservice
    username: root
    password: 1234
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis  # Tell Spring to use Redis for caching
  data:
    redis:
      host: localhost  # Change to "redis" if running in Docker
      port: 6388

  cloud:
    config:
      discovery:
        enabled: true  # Enable Eureka-based config server lookup
        service-id: config-server # <-- Eureka service name of your config server
    aws:
      region:
        static: us-east-2
  servlet:
    multipart:
      max-file-size: 5MB
      enabled: true
      max-request-size: 10MB
      file-size-threshold: 5MB

  config:
    import: "optional:configserver:"


server:
  port: 8082 # The service runs on this port

#The Gateway will also be registered at the Eureka server
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#logging:
#  level:
#    org.springframework.hibernate.sql: DEBUG
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.client: DEBUG
application:
  bucket:
    name: scmsjianlian